"""initial schema

Revision ID: c593aecdff25
Revises: 
Create Date: 2026-09-23 10:18:40.043871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c593aecdff25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_name'), ['name'], unique=True)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', 'transfer', name='categorykind'), nullable=False),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('exclude_from_totals', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    op.create_table('setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('statementimport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stored_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'extracting', 'classifying', 'review', 'done', 'error', name='importstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('low_confidence_count', sa.Integer(), nullable=False),
    sa.Column('reconcile_diff_cents', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statementimport', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statementimport_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statementimport_sha256'), ['sha256'], unique=True)

    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('counterparty', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classified_by', sa.Enum('rule', 'llm', 'user', name='classifiedby'), nullable=True),
    sa.Column('llm_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.Column('dedupe_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['statementimport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_dedupe_hash'), ['dedupe_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_transaction_import_id'), ['import_id'], unique=False)

    op.create_table('rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_from_txn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_from_txn_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_match_text'), ['match_text'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_match_text'))
        batch_op.drop_index(batch_op.f('ix_rule_category_id'))

    op.drop_table('rule')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_import_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_dedupe_hash'))
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_category_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    op.drop_table('transaction')
    with op.batch_alter_table('statementimport', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statementimport_sha256'))
        batch_op.drop_index(batch_op.f('ix_statementimport_account_id'))

    op.drop_table('statementimport')
    op.drop_table('setting')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))

    op.drop_table('category')
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_name'))

    op.drop_table('account')
    # ### end Alembic commands ###
